@baseUrl = http://localhost:3000/api

# Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
  "name": "Sam Sung"
}

###

# @name updateCategory
PATCH {{baseUrl}}/categories/2
Content-Type: application/json

{
  "name": "Samsung Galaxy"
}

###

# @name removeCategory
DELETE {{baseUrl}}/categories/3